### ISSUE TITLE
"Hello World!" box in moderator view

### ISSUE THREAD

**Issue by Varins** [enhancer-app/enhancer#50]
Hi, I've noticed there's a "Hello World!" box on top of my chat in mod view, and it covers half of the top gifters, I believe the problem might be connected to the "ChatIsland" module, it's the only module where i found "Hello World!" baked into the code (component.js)
![image](https://user-images.githubusercontent.com/24636077/201933170-ccb0d327-703c-40d7-9123-271724d54ba5.png)

This box appears only in mod view, normal view is completely fine

**Comment by animekkk** [comment]
quick fixed in 4713d0b57251ef882430a8c13470e62c37b65190
gonna work on it later

it should be updated tomorrow

**Comment by ngoudal** [comment]
Hi, I still see it when I enable the option "Hide Rooms Header" (which hides the "Stream Chat" header) of "FFZ Enhancing Add-On" (Chrome extension) in FrankerFaceZ

**Comment by igorovh** [comment]
In next week we are going to release new version of the extension and this notification is deleted.
